### ISSUE TITLE
Relint und Finalise Befehle

### ISSUE THREAD

**Issue by JonasunderscoreJones** [Lukas-Horst/epr_grader#2]
Hi,
Ich habe bei den letzten Abgaben alles bis auf den begin Befehl manuell gemacht, weil der epr_grader für die anderen beiden Befehle `relint` und `finalise` nicht korrekt funktioniert. Ich dachte zuerst, dass das an Linux liegt und habe deshalb angefangen einen fix dafür zu schreiben bis mir aufgefallen ist, dass das Programm fundamental nicht auf Linux läuft.

In meiner Windows VM habe ich dadurch keine Probleme mit `begin` mehr aber die mit den anderen beiden:

- Relint:
```
EPRgrader v3/221031 running on 2024-11-12 20:07:42.337528 [Windows-10 AMD64]
Traceback (most recent call last):
  File "Z:\epr_grader\eprgrader.py", line 493, in <module>
    main()
    ~~~~^^
  File "Z:\epr_grader\eprgrader.py", line 487, in main
    f.is_dir()], args.pairs, args.deduction)
                             ^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'deduction'
```
- Finalise:
Hier wird zunächst für jede Datei und ordner im `abgaben` Ordner jeder Abgabe ein Fehler angezeigt, dass diese keine `submission file` ist. So werden auch die Bewertungstabellen nicht erkannt und das Programm beendet sich mit einem Fehler für jede Datei.

Beim zweiten mal ausführen kommt es dann zu fehlern weil die `korrekturen`-Ordner für jede Person schon erstellt wird und dann kommt es zur folgenden Fehlermeldung:
```
PS Z:\abgaben\blatt02> python ..\..\epr_grader\eprgrader.py finalise
EPRgrader v3/221031 running on 2024-11-12 20:08:28.165672 [Windows-10 AMD64]
Copying grades...
Traceback (most recent call last):
  File "Z:\epr_grader\eprgrader.py", line 493, in <module>
    main()
    ~~~~^^
  File "Z:\epr_grader\eprgrader.py", line 489, in main
    finalise_grading(pathlib.Path(args.folder))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\epr_grader\eprgrader.py", line 321, in finalise_grading
    target.mkdir()
    ~~~~~~~~~~~~^^
  File "C:\Users\Jonas_Jones\AppData\Local\Programs\Python\Python313\Lib\pathlib\_local.py", line 722, in mkdir
    os.mkdir(self, mode)
    ~~~~~~~~^^^^^^^^^^^^
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'EPR07\\Zdravko Damnjanovic_797397_assignsubmission_file\\korrekturen'
```
Diesen **zweiten** fix für den `korrekturen`-Ordner habe ich eben lokal eingebaut, das ist kein Problem aber der erste ist mir auch vom Code her ein Rätsel weil das Pattern vom Dateinamen mit dem der Bewrtungstabelle und der stylechecker Datei übereinstimmen.

**Comment by Lukas-Horst** [comment]
Beim relint Befehl fehlte das deduction Argument. Habe das jetzt gefixt. Zu finalise... habe das in der Readme mal vermerkt.
